{''
 'name': 'Medical Store',
 'summary': """This module will add a record to store store details""",
 'version': '10.0.1.0.0',
'sequence':'-30',
 'description': """This module will add a record to store store details""",
 'author': 'Anzal',
 'company': 'Cybrosys Techno Solutions',
 'website': 'https://www.cybrosys.com',
 'category': 'Tools',
 'depends': [],
 'license': 'AGPL-3',
 'data': ['security/ir.model.access.csv',
'data/data.xml',
'wizard/create_invoice.xml',
'views/products.xml',
'views/tablet.xml',
'views/syrup.xml',
'views/oilment.xml',
'views/employee.xml',
'views/sales.xml',
'views/template.xml',
# 'views/website_form.xml',
          ],
 'demo': [],
 'installable': True,
 'auto_install': False,
 'application' : True
 }
