{''
 'name': 'Product Creation Restriction',
 'summary': """Custom Fields for ERP""",
 'version': '0.1',
 'sequence':'-580',
 'description': """Custom Access Rights""",
 'author': 'Ideenkreise Tech Pvt Ltd',
 'company': 'Ideenkreise Tech Pvt Ltd',
 'website': 'https://www.ideenkreisetech.com',
 'category': 'Tools',
  'depends': ['account','mrp','base','stock','base_accounting_kit','sale','sale_management'],
 'license': 'AGPL-3',
 'data': [
'security/group.xml',
'views/creation.xml',
'views/analytic.xml',
'views/description.xml',
'views/unlock.xml',
'views/bank.xml',
'views/lot_number.xml',
'views/delete.xml',
'views/confirmation.xml',
'views/external.xml',
'views/required.xml',
'views/cancel.xml',
'views/other_info.xml',

          ],
 'demo': [],
'images': ['static/description/icon.png'],
 'installable': True,
 'auto_install': False,
 'application' : True
 }
